CREATE TABLE VolCommand
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Cmd VARCHAR(1000) NOT NULL
);

CREATE TABLE PROFILE
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(100) NOT NULL,
	[Desc] VARCHAR(300) NOT NULL
);

CREATE TABLE Plugin
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(100) NOT NULL,
	[Desc] VARCHAR(300)
);

CREATE TABLE [Option]
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(100) NOT NULL,
	[Desc] VARCHAR(300) NOT NULL,
	[Type] VARCHAR(50) NOT NULL
);

CREATE TABLE PluginOption
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PluginID INTEGER NOT NULL,
	OptionID INTEGER NOT NULL,
	Required BIT,
	CONSTRAINT FK_PluginOption_Plugin FOREIGN KEY (PluginID) REFERENCES Plugin(ID),
	CONSTRAINT FK_PluginOption_Option FOREIGN KEY (OptionID) REFERENCES [Option](ID)
);

CREATE TABLE BatchFile
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(300) NOT NULL
);

CREATE TABLE BatchFilePlugin
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	BatchFileID INTEGER NOT NULL,
	PluginID INTEGER NOT NULL,
	CONSTRAINT FK_BatchFilePlugin_BatchFile FOREIGN KEY (BatchFileID) REFERENCES BatchFile(ID),
	CONSTRAINT FK_BatchFilePlugin_Plugin FOREIGN KEY (PluginID) REFERENCES Plugin(ID)
	
);
